# Generated by Django 4.1.1 on 2022-09-18 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productphoto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductPhoto',
        ),
    ]
