version: '3.9'
services:
  db:
    image: postgres
    container_name: postgres_db
    volumes:
      - .dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DATABASE = postgres
      - POSTGRES_DB = postgres
      - POSTGRES_USER = postgres
      - POSTGRES_PASSWORD = postgres
    ports:
      - "54322:5432"



  backend:
    container_name: backend
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db

